### ISSUE TITLE
[REQUEST] Topic specific news without specifying a website?

### ISSUE THREAD

**Issue by manugarri** [kotartemiy/newscatcher#10]
Would it be possible to get the tech headlines without specifying a website?

**Comment by 0xYasser** [comment]
Like this? 
``` Python
 tech_headlines = [Newscatcher(source).get_headlines() for source in urls(topic = 'tech', language='en')]
```
be carful tho it's going to be a huge number of requests

**Comment by BecketTrotter** [comment]
@0xYasser urls has an optional n parameter to limit results

**Comment by kotartemiy** [comment]
Yes, that's how you could do it
> Like this?
> 
> ```python
>  tech_headlines = [Newscatcher(source).get_headlines() for source in urls(topic = 'tech', language='en')]
> ```
> 
> be carful tho it's going to be a huge number of requests
