### ISSUE TITLE
Exception raised on 'news.ycombinator.com'

### ISSUE THREAD

**Issue by christianboyle** [kotartemiy/newscatcher#2]
Cool project, everything seems to work as intended, but for some reason trying to use `news.ycombinator.com` as the `news_source` raises `Exception: check internet connection / website is not supported`. 

It's odd, because other sources with subdomains work without issue, such as `wired.co.uk`.

**Comment by kotartemiy** [comment]
Hey. thx. 
I just tested with `website = Newscatcher('news.ycombinator.com')`

It works. Probably you made an error somewhere.

If still does not work, please, share the full code.
