### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by mrbill007** [kotartemiy/newscatcher#7]
Am I doing something wrong to receive this error?

![newscatcher error](https://user-images.githubusercontent.com/10362376/75817205-7ed46300-5d4b-11ea-9e13-b83bee1ce924.jpg)

**Comment by kotartemiy** [comment]
What is your python version?

`python -V`
or
`python3 -V`

**Comment by mrbill007** [comment]
![newscatcher_install_failure](https://user-images.githubusercontent.com/10362376/76026709-2c7a7a00-5ee4-11ea-8469-8126dea374b5.jpg)

3.6.9

**Comment by MastafaF** [comment]
Same here, not working on google colab with python 3 (and python 2), as is.

**Comment by gerryvk** [comment]
Try pip3 install newscatcher

**Comment by mrbill007** [comment]
Thanks, I appreciate the reply, but still no luck.

![image](https://user-images.githubusercontent.com/10362376/77566845-7c18e980-6e83-11ea-923d-5528390673ec.png)

**Comment by 0xYasser** [comment]
@mrbill007 looks like your network is blocking, or has it's own pypi index which was't updated at that time. do you still have the issue?
